default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: localhost
  password: 12345678
  # password: postgres

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
